name: Build and Release Executables

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Download and Install Ghostscript
        if: runner.os == 'Windows'
        run: |
          Invoke-WebRequest -Uri "https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs1000/gs1000w32.exe" -OutFile "ghostscript_installer.exe"
          Start-Process -FilePath "ghostscript_installer.exe" -ArgumentList "/S" -Wait
          echo "Ghostscript installed"

      - name: Build executable for Linux
        if: runner.os == 'Linux'
        run: |
          pyinstaller --onefile --name PDFCompressor main.py
  
      - name: Build executable for Windows
        if: runner.os == 'Windows'
        run: |
          python3 -m PyInstaller --onefile --windowed --name PDFCompressor main.py

      - name: Upload executable as artifact for Linux
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: Executables
          path: |
            dist/PDFCompressor

      - name: Upload executable as artifact for Windows
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: Executables
          path: |
            dist/PDFCompressor.exe

      - name: Create Release for Linux
        if: runner.os == 'Linux'
        id: create_release_for_linux
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}-linux
          files: |
            dist/PDFCompressor
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release for Windows
        if: runner.os == 'Windows'
        id: create_release_for_windows
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}-windows
          files: |
            dist/PDFCompressor.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
